server:
  port: 8088
#  error:
#    path: /error

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/fanruidemo
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
  thymeleaf:
      content-type: text/html
      cache: false
      mode: LEGACYHTML5
      prefix: classpath:/templates
      suffix: .html
